#!/bin/bash
#source /usr/lib/elive-tools/functions
# elive functions {{{
el_confirm(){
    # pre {{{
    local reply question flag_glob

    question="$1"

    # }}}
    # return answer {{{

    echo -en "\n$question [y/n]: "
    if [[ -n "$ZSH_VERSION" ]] ; then
        read reply
    else
        read -e reply
    fi

    case "$reply" in
        y|Y|Yes|YES|s|S)
            return  0
            ;;
        n|N|no|NO|nope)
            return  1
            ;;
        *)
            # repeat question until confirmation
            if el_confirm "${el_c_b2}${@}${el_c_n}" ; then
                return 0
            else
                return 1
            fi
            ;;
    esac

    # }}}
}
# - elive functions }}}

main(){
    set -e
    branch="main"

    cd ~/.config/nvim

    echo -en "Updating..."
    command git fetch -q origin ${branch}
    echo -e "Updated       "

    if [[ "$( cat .git/refs/remotes/origin/${branch} )" != "$( cat .git/HEAD )" ]] ; then
        echo "updates available"
        command git log -q --graph --all --format=format:'%C(bold blue)%h%C(reset) - %C(bold cyan)%aD%C(reset) %C(bold green)(%ar)%C(reset) %C(bold yellow)%an%C(reset)%n''          %C(bold white)%s%C(reset) %C(white)%b%C(reset)' HEAD...refs/remotes/origin/${branch}
        if el_confirm "Do you want to include updates?" ; then

            echo -e "Please restart NeoVim"
        fi
    fi

    nvim "$@"
}

#
#  MAIN
#
main "$@"

# vim: set foldmethod=marker :
